### PR TITLE
Increase membersWithEmptyAssignment when MemberAssignment is empty

### PR DESCRIPTION
**Pull request by Sh1ftry**
Fix for https://github.com/redpanda-data/kminion/issues/141

### CODE REVIEW

**Comment by amuraru** [comment]
Good catch @Sh1ftry  +1

**Comment by doryer** [comment]
@weeco @amuraru Waiting also for approval, Thanks

**Comment by doryer** [comment]
@weeco @amuraru Waiting also for approval, Thanks

**Review by weeco — APPROVED** [review]

**Comment by weeco** [comment]
Thank you @Sh1ftry ! Sorry for the delay, I haven't got any notifications from GitHub lately.

**Comment by weeco** [comment]
@amexboy Currently we are moving the build pipelines and docker registry from CloudHut to Redpanda Data due to the recent acquisition (see: https://cloudhut.dev/blog/2022-04-01-redpanda-acquires-cloudhut-kowl/), hence they do not yet work. I plan to fix the build pipeline by the end of this week though. Sorry!

**Comment by amexboy** [comment]
That would be awesome! Thank you so much

**Comment by weeco** [comment]
@amexboy Sorry it took longer than expected, but docker builds are now available under: https://hub.docker.com/r/vectorized/kminion/tags

**Comment by amexboy** [comment]
@weeco  Thank you so much. I will give it a spin

**Pull request merged**
